server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - x-client-id
              - X-Client-Id
            exposedHeaders:
              - x-client-id
              - X-Client-Id
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

      discovery:
        locator:
          enabled: true

      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/Category/**, /Product/**, /uploads/**
          filters:
            - AuthFilter
            
        - id: ms-client-service
          uri: lb://ms-client-service
          predicates:
            - Path=/Client/**
          filters:
            - AuthFilter

        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/Order/**
          filters:
            - AuthFilter

        - id: ms-venta-service
          uri: lb://ms-venta-service
          predicates:
            - Path=/Sale/**, /reports/**
          filters:
            - AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
